// Raw clips from real coaching calls, shown in the video wall on /coaching.
// Captions are word for word from the audio (stutters removed). First names only. Strongest first.
// Files live in /public/testimonials/results/<slug>.mp4 + .jpg
export const RESULT_CLIPS = [
  { slug: "josh-1", who: "Josh", cap: "You've removed money from the pedestal for me… I am in control of it. It is not in control of me." },
  { slug: "josh-2", who: "Josh", cap: "Book that first call. Just do it. One call is all it takes." },
  { slug: "josh-4", who: "Josh", cap: "I've paid myself. According to your advice, I paid myself… my credit cards are basically all done now." },
  { slug: "josh-3", who: "Josh", cap: "It felt like two boys having conversations about things I was ashamed of. That's a massive shift, the way I talk about money now." },
  { slug: "alon-2", who: "Alon", cap: "When we actually looked over the numbers, it made everything clearer, and that fear really went away." },
  { slug: "alon-4", who: "Alon", cap: "Before, if you make decisions and then you're like, \"Oh, I don't want to look at the bank account because I know it's gone down,\" I've kind of stopped having that." },
  { slug: "alon-6", who: "Alon", cap: "I feel like almost a reset in my life. It's like a new life for me." },
  { slug: "alon-3", who: "Alon", cap: "When I have the calls with you, it doesn't feel like I'm speaking to you about money. It's more like life planning." },
  { slug: "alon-5", who: "Alon", cap: "The best this kind of program works is when you truly give the person the full-on stage to expose themselves first, and from there you work." },
  { slug: "alon-1", who: "Alon", cap: "I realized, with one of our talks, how money is opportunity. And then I realized I have a lot of dreams of my own, and for us to get there in this world, we need that money." },
  { slug: "alex-2", who: "Alex", cap: "I never would have got there without you. Never. I can 100% say that." },
  { slug: "alex-1", who: "Alex", cap: "In eight weeks I already feel like I probably wouldn't have learned that in four or five years." },
  { slug: "alex-3", who: "Alex", cap: "That money strain is not there. Definitely having that extra long buffer before it gets to money's getting tight." },
  { slug: "hozz-4", who: "Hozir", cap: "Anxiety around money at the start: \"probably around nine, ten.\" Now: \"maybe four or five.\"" },
  { slug: "hozz-1", who: "Hozir", cap: "It feels like it's been ages, working with you. The worksheets and the whole stuff brought everything together, and you made the person feel like, \"Yeah, it's possible.\"" },
  { slug: "hozz-3", who: "Hozir", cap: "I have actually learned a lot in terms of the money psychology, my own triggers. Now I'm realising the whole picture." },
  { slug: "jen-4", who: "Jennifer", cap: "It wasn't just about learning new money tools, but actually being taken by the hand, kind of guided through this process, and also being given a type of system or structure I can apply no matter how much money I have available. That is really huge." },
  { slug: "jen-1", who: "Jennifer", cap: "I was so grateful knowing that I'm dealing with all these things right now, and there's this shift happening, but I don't have to deal with it alone." },
  { slug: "jen-2", who: "Jennifer", cap: "Tracking my spending, feeling more comfortable. I feel so certain that what I'm doing right now is the right thing for me." },
  { slug: "jen-3", who: "Jennifer", cap: "They always ask me, \"How's the work going with Joel?\" I told them about you." },
  { slug: "lynt-1", who: "Lynton", cap: "I had my car serviced this week, and I didn't once flicker at the idea of what it was going to cost me." },
  { slug: "lynt-3", who: "Lynton", cap: "I've cleaned up my spending, I've put my structured payments into place… I have a plan, I have a system, and that's been working." },
  { slug: "lynt-2", who: "Lynton", cap: "Thank God Joel came into my life. All he did was redirect my habits, and now I've got my systems in place." },
  { slug: "lynt-4", who: "Lynton", cap: "There has been progress in decision-making, what you teach me, behavioural economics… those things have really started to become more relevant." },
  { slug: "lynt-5", who: "Lynton", cap: "I did read through the report. It was really eye-opening." },
  { slug: "sham-1", who: "Shambhavi", cap: "I never had the opportunity to have someone guide me through the process and see how it's kind of making it worse rather than helping anything." },
  { slug: "zachi-1", who: "Zachi", cap: "I didn't expect to see change this soon, but I'm happy that I did. I'm already making changes I didn't expect to ever see." },
  { slug: "zachi-2", who: "Zachi", cap: "I'm confronting something that I ran away from." },
  { slug: "shira-2", who: "Shira", cap: "I have had a shift in mindset, especially in not thinking about money as much as the devil." },
  { slug: "shira-3", who: "Shira", cap: "I probably do feel less like money is the enemy." },
  { slug: "shira-4", who: "Shira", cap: "I would say do it, even if you feel resistant to it." },
  { slug: "shira-5", who: "Shira", cap: "The money will follow. And I'm not necessarily thinking of the money, but it's inspiring me to just start." },
  { slug: "shira-1", who: "Shira", cap: "It inspires me to try and work on it." },
  { slug: "naomi-1", who: "Naomi", cap: "I was actually more kind of mindful this week. Like, \"Do I need this?\" Like pausing before I bought something." },
  { slug: "eden-2", who: "Eden", cap: "I was doing your worksheets, it got me thinking more, and I made much better decisions." },
  { slug: "eden-3", who: "Eden", cap: "You need to know somebody's financial behaviour before it's a serious thing." },
  { slug: "eden-1", who: "Eden", cap: "I think you're the perfect level of chill, and going on odd conversations but bringing it back to what you need to." },
  { slug: "sam-1", who: "Sam", cap: "Now I would say it's more collaborative. If money walked into a bar, I think money would approach me and be like, \"What's the plan?\"" },
  { slug: "sam-2", who: "Sam", cap: "I said that to you, and you've been like, \"Okay, let's explore that.\"" },
  { slug: "sam-g-1", who: "Sam G", cap: "It's quite motivating to talk about money. You're putting it at the front of your mind." },
  { slug: "japhet-1", who: "Japhet", cap: "I'm glad I have someone to talk to about it." },
  { slug: "jess-1", who: "Jessica", cap: "I know that you're uncovering things for me and helping me. It's really good to have a mirror." },
  { slug: "hozz-2", who: "Hozir", cap: "I love the belief systems. I would like to alleviate that feeling that personal spending is not allowed." },
];
